### ISSUE TITLE
general updates to package:dart_flutter_team_lints

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/ecosystem#110]
We should do a redux of package:dart_flutter_team_lints - update it for lints we're mostly always turning on for dart repos.

Here are the lints enabled on for dart-lang repos that are already using `package:dart_flutter_team_lints`:

| Lint | Occurrences |
| --- | --- |
| https://dart.dev/lints/test_types_in_equals | 29 |
| https://dart.dev/lints/package_api_docs | 29 |
| https://dart.dev/lints/prefer_relative_imports | 28 |
| https://dart.dev/lints/avoid_unused_constructor_parameters | 28 |
| https://dart.dev/lints/cancel_subscriptions | 27 |
| https://dart.dev/lints/comment_references | 23 |
| https://dart.dev/lints/use_super_parameters | 22 |
| https://dart.dev/lints/prefer_const_constructors | 22 |
| https://dart.dev/lints/no_adjacent_strings_in_list | 22 |
| https://dart.dev/lints/literal_only_boolean_expressions | 21 |
| https://dart.dev/lints/no_runtimeType_toString | 20 |
| https://dart.dev/lints/avoid_private_typedef_functions | 20 |
| https://dart.dev/lints/prefer_final_locals | 19 |
| https://dart.dev/lints/prefer_const_declarations | 19 |
| https://dart.dev/lints/use_string_buffers | 18 |
| https://dart.dev/lints/prefer_expression_function_bodies | 18 |
| https://dart.dev/lints/missing_whitespace_between_adjacent_strings | 18 |
| https://dart.dev/lints/unnecessary_await_in_return | 17 |
| https://dart.dev/lints/join_return_with_assignment | 17 |
| https://dart.dev/lints/avoid_redundant_argument_values | 17 |
| https://dart.dev/lints/avoid_void_async | 13 |
| https://dart.dev/lints/avoid_returning_this | 13 |
| https://dart.dev/lints/avoid_returning_null | 13 |
| https://dart.dev/lints/avoid_bool_literals_in_conditional_expressions | 13 |
| https://dart.dev/lints/avoid_returning_null_for_future | 12 |
| https://dart.dev/lints/avoid_classes_with_only_static_members | 12 |
| https://dart.dev/lints/cascade_invocations | 9 |
| https://dart.dev/lints/use_raw_strings | 6 |
| https://dart.dev/lints/use_if_null_to_convert_nulls_to_bools | 6 |
| https://dart.dev/lints/unnecessary_raw_strings | 4 |
| https://dart.dev/lints/require_trailing_commas | 3 |
| https://dart.dev/lints/prefer_final_in_for_each | 3 |
| https://dart.dev/lints/prefer_mixin | 2 |
| https://dart.dev/lints/camel_case_types | 2 |
| https://dart.dev/lints/avoid_catches_without_on_clauses | 2 |

I suggest we add the top ~10 in that list - down through and including `literal_only_boolean_expressions`. Are there any others we should include, or any of the first 10 that we should exclude?

**Comment by parlough** [comment]
One thing that has been a challenge for me is the lack of the lints from `flutter_lints` when working on Flutter tools. Right now I have to choose from `dart_flutter_team_lints` or `flutter_lints` and add the other's lints back. 

Perhaps this set can be based on `flutter_lints` instead or add its own Flutter set?

**Comment by devoncarew** [comment]
> when working on Flutter tools

Which tools? Are they flutter repos or flutter apps?

I think the general idea here is that this rule set is the rules on top of package:lints/recommended that we (the dart team) want to use for our own code but for one reason or another don't want to generally recommend to the community. The Flutter rules sets (https://github.com/flutter/flutter/blob/master/analysis_options.yaml, https://github.com/flutter/packages/blob/master_archive/analysis_options.yaml, ...) could then re-host on top of this set.

**Comment by parlough** [comment]
I'm fine having to re-host on top of this set. 

My thinking was for Flutter apps created by the Dart (or Flutter) team, [`dart_pr_dashboard`](https://github.com/mosuem/dart_pr_dashboard), SketchPad, a Flutter based replacement of the Flutter samples index I'm working on, perhaps DevTools, etc. Perhaps it's best for the Flutter team to introduce a packaged set, but since this package already exists and includes `flutter` in the name, I thought it might be a good place for it.

**Comment by parlough** [comment]
As for adding the top 10 you mentioned, they all seem like good choices to me that I would enable as well. I know some developers prefer `always_use_package_imports` over `prefer_relative_imports`, but the only package I've touched that uses it is the analyzer.
