### ISSUE TITLE
Package tag body does not have linebreaks

### ISSUE THREAD

**Issue by mosuem** [dart-lang/ecosystem#135]
When clicking on the tag in the comment created by the autopublish action, the changelog items are joined without line separators. Maybe https://github.com/dart-lang/ecosystem/blob/db9d71d8428bc7a46d618dc5bfc4ee189933b0a1/pkgs/firehose/lib/src/changelog.dart#L88 needs to be adapted?

See for example by clicking the tag link in https://github.com/dart-lang/ecosystem/pull/132#issuecomment-1630511201.

**Comment by devoncarew** [comment]
this was fixed by https://github.com/dart-lang/ecosystem/pull/180
