### ISSUE TITLE
allow firehose to write comments to PRs from forks

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/ecosystem#156]
I believe there is some permissions work we can do to allow firehose to write comments to PRs from forks (currently it can write the workflow summary but not a comment to the PR; the PR comment is *much* more visible to users).

cc @mosuem

**Comment by mosuem** [comment]
This would basically be achieved by uploading the comment as an artifact, triggering a second workflow, downloading the artifact there and publishing it as a comment.
