### ISSUE TITLE
auto publishing comment table order

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/ecosystem#200]
See https://github.com/dart-lang/native/pull/810#issuecomment-1817943308

<img width="727" alt="image" src="https://github.com/dart-lang/ecosystem/assets/3601775/51a7a620-b767-4831-8780-7f7617881a70">

I think I would prefer alphabetical ordering of the that table.

**Comment by devoncarew** [comment]
> I think I would prefer alphabetical ordering of the that table.

Hmm, I wonder if we're defaulting to some file listing order?
