### ISSUE TITLE
Include `invalid_runtime_check_with_js_interop_types` when the min SDK is updated to 3.5

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/ecosystem#279]
https://dart.dev/tools/linter-rules/invalid_runtime_check_with_js_interop_types

This should be enforced without exception!

**Comment by devoncarew** [comment]
Related discussion on this lint at https://github.com/dart-lang/lints/issues/188.

**Comment by devoncarew** [comment]
Lets hold off on considering this for dart_flutter_team_lints until we resolve the package:lints discussion.

**Comment by devoncarew** [comment]
addressed by https://github.com/dart-lang/ecosystem/pull/285
