### ISSUE TITLE
Lints: consider adding new 2.19 lints

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/ecosystem#47]
- collection_methods_unrelated_type
- combinators_ordering
- dangling_library_doc_comments
- implicit_call_tearoffs
- library_annotations
- unnecessary_library_directive
- unreachable_from_main
- use_string_in_part_of_directives

I wish the combinators_ordering one was case-insensitive, though!

**Comment by devoncarew** [comment]
> I wish the combinators_ordering one was case-insensitive, though!

cc @pq re: `combinators_ordering`; happy to file a feature request if that change sounds reasonable.

**Comment by kevmoo** [comment]
I think we already argued about this. I'm not sure....

I mean, had a thoughtful discussion 😁

**Comment by pq** [comment]
> I think we already argued about this. I'm not sure....

😃 

https://github.com/dart-lang/linter/issues/3866
