### ISSUE TITLE
Rpc error in validate packages step

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/ecosystem#56]
See https://github.com/dart-lang/args/actions/runs/4115484830/jobs/7104258106#step:5:113, not sure if we need to do something to give it better credentials or if generally this can be handled better.

**Comment by devoncarew** [comment]
Thanks for the report! Things look like they're configured correctly. I think I'll wait until we've seen this a few more times before putting in guard code (perhaps this was an isolated incident w/ github?).

For posterity, the exception was when we tried to write back a 'package validated; tag w/ xxx to publish' comment to the PR.

```
RpcException: Forbidden
#0      Github.callRestApiPost.<anonymous closure> (package:firehose/src/github.dart:66:13)
<asynchronous suspension>
#1      Github.createComment (package:firehose/src/github.dart:104:18)
<asynchronous suspension>
#2      Firehose.validate (package:firehose/firehose.dart:62:9)
...
```

**Comment by jakemac53** [comment]
Could we be getting rate limited? It looks like you get a 403 forbidden response when that happens.

**Comment by devoncarew** [comment]
Possibly? I wouldn't think so, as we're authenticated at the point of the call.

**Comment by jakemac53** [comment]
It also looks like we aren't providing a user agent, which the docs say is required, but it clearly works on other repos...

**Comment by jakemac53** [comment]
But in any case the increased logging should help figure out what is up :)

**Comment by jakemac53** [comment]
I believe this is because the pull request is coming from a "public forked repo", and according to [this](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs) that only assigns read permission?

It seems wrong that it can't even comment on the PR, but based on the message [here](https://github.com/dart-lang/args/actions/runs/4115484830/jobs/7111798867#step:5:112) "Resource not accessible by integration" that seems to be a likely cause.

**Comment by jakemac53** [comment]
There is this note though(from [here](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview)) :

You can use the permissions key to add and remove read permissions for forked repositories, but typically you can't grant write access. The exception to this behavior is where an admin user has selected the Send write tokens to workflows from pull requests option in the GitHub Actions settings. For more information, see "[Managing GitHub Actions settings for a repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#enabling-workflows-for-private-repository-forks)."

**Comment by devoncarew** [comment]
Yeah, the above makes sense. I don't think I want to elevate permissions for incoming PRs. If we can't rely on being able to create comments on the PR, that may mean pivoting back to just using github action summaries.
