### ISSUE TITLE
Publish is not running on a push?

### ISSUE THREAD

**Issue by annagrin** [dart-lang/ecosystem#75]
We have automated publishing in webdev repo, thanks @kevmoo for adding the configuration, this is awesome!

A couple of issues the I encountered when I used it (I think it is for the first time) in https://github.com/dart-lang/webdev/pull/1993

- Even if the configuration is meant to run using main SDK channel, it still run using stable and failed due the lower SDK constraint we have in dwds.
  - See the configuration added here: https://github.com/dart-lang/webdev/commit/7575ebd22a99e360f065bbb8aba2fc651bb20c43#r101991750
  - Logs from the failing publish task:
     https://github.com/dart-lang/webdev/actions/runs/4265572537/jobs/7425052308:

     ```
     dart pub publish --dry-run
        Resolving dependencies...
        The current Dart SDK version is 2.19.2.
  
     Because dwds requires SDK version >=3.0.0-188.0.dev <4.0.0, version solving failed.
     ```

- I changed the configuration to run publish using dev channel, but the publish task disappeared. 

First push:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/12737689/221284124-2b81e445-278c-48fa-b72a-25014d07cc15.png">

Second push:

<img width="514" alt="image" src="https://user-images.githubusercontent.com/12737689/221284279-ce1b0bb7-43a0-49d0-9702-59468ac1030d.png">

**Comment by kevmoo** [comment]
@devoncarew ?

**Comment by annagrin** [comment]
@devoncarew I misunderstood the meaning of @main here. We don't have a main branch, should this be @master instead? 
 And the main question - is there a way to I make publish run using dev SDK channel?

**Comment by devoncarew** [comment]
Ok, so from my understanding:

- you've updated the publishing task to run from a `dev` sdk
- you're seeing this warning from the publish; that's failing the validation task
- this is a warning you'd see from the command line if you manually ran `dart pub publish --dry-run` using a dev sdk

Is that all correct? If so, it sounds like this is a warning that you knowingly want to ignore, but that our CI is failing on. Short term, you should be able to ignore the failing and merge the PR w/ that one red bot. The publishing task (when you tag master w/ the right tag - I assume something like `dwds-v18.0.0`) _should_ still succeed. It'll run the publish with `dart pub publish --force`, and I think will ignore the warning.

Longer term, we should have a way to configure that this warning is acceptable to us. That could be a flag in the publish config file - `disregard-warnings`. Or perhaps, when a publish bot fails, a repo maintainer could add a label - `publishing-ignore-warnings` to indicate that the warnings are not blockers.

**Comment by annagrin** [comment]
@devoncarew this is correct. I am disabling the publishing verification for now in favor of manual one until we have support for disabling some warnings.

**Comment by devoncarew** [comment]
OK, sounds good (though FYI, you should be able to land the PR even with the red bot - the validation failure - and then still use the publishing automation via tagging the commit in master). Publishing manually would also work.

**Comment by annagrin** [comment]
Thanks! I prefer the bot to be green though, we will re-enable the check as soon as it can work for us, as it indeed a very useful feature.

**Comment by devoncarew** [comment]
I'm going to close this; we also have https://github.com/dart-lang/ecosystem/issues/64, which is similiar.
