### ISSUE TITLE
Add lints: always_declare_return_types

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/ecosystem#79]
seems like no-brainers

https://dart-lang.github.io/linter/lints/always_declare_return_types.html

**Comment by devoncarew** [comment]
`use_super_parameters` ?

**Comment by kevmoo** [comment]
> `use_super_parameters` ?

I love that lint, but there's a bug at the moment – in the analyzer. We should probably hold off until it's fixed.

**Comment by devoncarew** [comment]
Hmm, closing this as it looks like we already have that lint enabled:

https://github.com/dart-lang/ecosystem/blob/main/pkgs/dart_flutter_team_lints/lib/analysis_options.yaml#L52
